"""Remover admin do usuario

Revision ID: 358c76bd4c43
Revises: 512e693303d1
Create Date: 2025-11-24 13:25:03.295589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358c76bd4c43'
down_revision: Union[str, Sequence[str], None] = '512e693303d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
